# Site settings
title: DYD Blog
SEOTitle: DYD的博客 | DYD Blog
header-img: img/post-bg-rwd.jpg
email: mtnk2009@163.com
description: "万物皆有裂痕，要看到裂痕中照进来的光，而不是裂痕本身"
keyword: "DYD, DYD Blog, DYD的博客, daiyadong, 代亚东, iOS, Apple, iPhone"
#url: "http://daiyadong.github.io"          # your host, for absolute URL
url: "https://netsec.today"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/daiyadong/daiyadong.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我思故我在，黑掉全世界，挺押韵的哈。"
sidebar-avatar: /img/dyd.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
weibo_username:     7330194699
#zhihu_username:     dai-ya-dong-36
jianshu_username:   d326b96789be
github_username:    daiyadong
facebook_username:  yadong.dai.9
twitter_username:   daiyadong




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7d67798470859164b3ce #生成的clientID
  clientSecret: 52b32e849ce7474b11135500e37c55ec17b2364f    #生成的clientSecret
  repo: daiyadong.github.io    #仓库名称
  owner: daiyadong #github用户名
  admin: daiyadong
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: d4935820d17f00bdb5b757e5db1e34ae

# Google Analytics
ga_track_id: 'UA-150799772-1'            # Format: UA-xxxxxx-xx
ga_domain: netsec.today                  # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    },{
        title: "cnblogs",
        href: "https://cnblogs.com/"
    },{
        title: "01hackcode",
        href: "http://01hackcode.com"
   }
]
